DROP DATABASE IF EXISTS arzneiversand;
CREATE DATABASE arzneiversand;
use arzneiversand;

CREATE TABLE Kunde (
	K_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name Varchar(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_german1_ci;

CREATE TABLE Zusteller (
	Z_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name Varchar(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_german1_ci;

CREATE TABLE Arzneimittel(
	A_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name Varchar(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_german1_ci;

CREATE TABLE Lieferung (
	L_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    K_ID INTEGER NOT NULL,
    Z_ID INTEGER NOT NULL,
    CONSTRAINT K_ID FOREIGN KEY (K_ID) REFERENCES Kunde (K_ID),
    CONSTRAINT Z_ID FOREIGN KEY (Z_ID) REFERENCES Zusteller (Z_ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_german1_ci;

CREATE TABLE Paket(
	P_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    L_ID INTEGER NOT NULL,
    CONSTRAINT L_ID FOREIGN KEY (L_ID) REFERENCES Lieferung (L_ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_german1_ci;

CREATE TABLE Link_P_A(
	P_ID INTEGER NOT NULL,
    A_ID INTEGER NOT NULL,
	CONSTRAINT PrimaryKey PRIMARY KEY (A_ID, P_ID),
    CONSTRAINT A_ID FOREIGN KEY (A_ID) REFERENCES Arzneimittel (A_ID),
    CONSTRAINT P_ID FOREIGN KEY (P_ID) REFERENCES Paket (P_ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE latin1_german1_ci;